// This is an autogenerated file, please do not change anything here

import { apacheconf } from './apacheconf';
import { bash } from './bash';
import { clike } from './clike';
import { css } from './css';
import { diff } from './diff';
import { haskell } from './haskell';
import { http } from './http';
import { ini } from './ini';
import { javascript } from './javascript';
import { json } from './json';
import { jsx } from './jsx';
import { less } from './less';
import { makefile } from './makefile';
import { markdown } from './markdown';
import { markup } from './markup';
import { matlab } from './matlab';
import { php } from './php';
import { python } from './python';
import { ruby } from './ruby';
import { scss } from './scss';
import { sql } from './sql';
import { typescript } from './typescript';
import { yaml } from './yaml';

export {
    apacheconf,
    bash,
    clike,
    css,
    diff,
    haskell,
    http,
    ini,
    javascript,
    json,
    jsx,
    less,
    makefile,
    markdown,
    markup,
    matlab,
    php,
    python,
    ruby,
    scss,
    sql,
    typescript,
    yaml,
    markup as html,
    javascript as js,
    json as json5,
    markdown as md,
    typescript as ts
};
