const fs = require('fs');
const path = require('path');
const aliases = require('../src/aliases.json');

const langs = fs.readdirSync(path.resolve(__dirname, '../src/languages'), 'utf8');

const header = `// This is an autogenerated file, please do not change anything here`;

const imports = [];
const exp = [];

langs.forEach(lang => {
    if (lang === '__tests__' || lang === 'index.ts') return;

    l = lang.replace('.ts', '');

    imports.push(`import { ${l} } from './${l}';`);
    exp.push(l);
});

Object.keys(aliases).forEach(key => {
    exp.push(`${aliases[key]} as ${key}`);
});

const file = `// This is an autogenerated file, please do not change anything here

${imports.join('\n')}

export {
    ${exp.join(',\n    ')}
};
`;

fs.writeFileSync(path.resolve(__dirname, '../src/languages/index.ts'), file, 'utf8');
